elastic-query-service:
  version: v1

server:
  port: 8183
  servlet:
    context-path: /elastic-query-service

elastic-query-config:
  text-field: text

elastic-config:
  index-name: twitter-index
  connection-url: http://localhost:9200
  connect-timeout-ms: 5000
  socket-timeout-ms: 30000

user-config: #test/test
  username: test
  password: '{cipher}ce28405be2aa895fd30ab534e7dcf09aeb433682efc1f94c33cf94bbf8eb94c0'
  roles: USER

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

security:
  paths-to-ignore: /api-docs