elastic-query-service:
  version: v1
#  custom-audience: elastic-query-service
  webclient:
    connect-timeout-ms: 10000
    read-timeout-ms: 10000
    write-timeout-ms: 10000
    max-in-memory-size: 10485760 # 10MB
    content-type: 'application/vnd.api.v1+json'
    accept-type: 'application/vnd.api.v1+json'
    query-type: '${QUERY_TYPE}'
  query-from-kafka-state-store:
    method: GET
    uri: "http://localhost:8187/kafka-streams-service/get-word-count-by-word/{word}"
    accept: ${elastic-query-service.webclient.accept-type}
  query-from-analytics-database:
    method: GET
    uri: "http://localhost:8188/analytics-service/get-word-count-by-word/{word}"
    accept: ${elastic-query-service.webclient.accept-type}

server:
  port: 8183
  servlet:
    context-path: /elastic-query-service

#spring:
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: http://localhost:8081/auth/realms/microservices-realm
#          jwk-set-uri: http://localhost:8081/auth/realms/microservices-realm/protocol/openid-connect/certs
#  jpa:
#    open-in-view: false
#    show-sql: true
#    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQL9Dialect
#  datasource:
#    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=public&binaryTransfer=true&reWriteBatchedInserts=true
#    username: postgres
#    password: '{cipher}43f602928cfaa75b99fe65a175aca66f01e25825ad59e01e896342f0653335d3'
#    driver-class-name: org.postgresql.Driver
#    platform: postgres
#    schema: classpath:init-schema.sql
#    data: classpath:init-data.sql
#    initialization-mode: always

elastic-query-config:
  text-field: text

elastic-config:
  index-name: twitter-index
  connection-url: http://localhost:9200
  connect-timeout-ms: 5000
  socket-timeout-ms: 30000

# for simplicity
user-config: #test/test
  username: test
  password: '{cipher}ce28405be2aa895fd30ab534e7dcf09aeb433682efc1f94c33cf94bbf8eb94c0'
  roles: USER

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

security:
  paths-to-ignore: /api-docs